parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/orm/api'
                prefix: 'App\Entity'
                alias: App
            Core:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/orm/core'
                prefix: Novosga\Entity
                alias: Novosga
