language: php

dist: trusty
sudo: false

php:
    - 7.1

git:
    depth: 1

env:
    global:
        - LANGUAGE="en"
        - APP_ENV="prod"
        - DATABASE_URL="mysql://root@127.0.0.1:3306/db?charset=utf8mb4&serverVersion=5.7"

install:
    - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
    - php vendor/bin/phpcs
    - php bin/phpunit
    
after_success:
    - travis_retry composer install --no-dev --no-interaction --prefer-dist --no-suggest

cache:
    directories:
        - $HOME/.composer/cache