App\Entity\OAuthClient:
    type: entity
    table: oauth_clients
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            length: 30