Novosga\Entity\AbstractAtendimentoCodificado:
    type: mappedSuperclass
    id:
        servico:
            associationKey: true
    fields:
        peso:
            type: smallint
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: valor_peso
    manyToOne:
        servico:
            targetEntity: Novosga\Entity\Servico
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                servico_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
