Novosga\Entity\Atendimento:
    type: entity
    table: atendimentos
    repositoryClass: App\Repository\ORM\AtendimentoRepository
    oneToMany:
        codificados:
            targetEntity: Novosga\Entity\AtendimentoCodificado
            cascade: {  }
            fetch: LAZY
            mappedBy: atendimento
            orphanRemoval: false
            orderBy: null
