Novosga\Entity\Cliente:
    type: entity
    table: clientes
    repositoryClass: App\Repository\ORM\ClienteRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            length: 60
            nullable: false
            column: nome
        documento:
            type: string
            length: 30
            nullable: false
            column: documento
        email:
            type: string
            length: 80
            nullable: true
            column: email