Novosga\Entity\ClienteMeta:
    type: entity
    table: clientes_metadata
    repositoryClass: App\Repository\ORM\EntityMetadataRepository
    id:
        entity:
            associationKey: true
    manyToOne:
        entity:
            targetEntity: Novosga\Entity\Cliente
            fetch: LAZY
            joinColumns:
                cliente_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
