Novosga\Entity\PainelServico:
    type: entity
    table: paineis_servicos
    id:
        painel:
            associationKey: true
        servico:
            associationKey: true
    manyToOne:
        painel:
            targetEntity: Novosga\Entity\Painel
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                host:
                    referencedColumnName: host
            orphanRemoval: false
        servico:
            targetEntity: Novosga\Entity\Servico
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                servico_id:
                    referencedColumnName: id
            orphanRemoval: false
        unidade:
            targetEntity: Novosga\Entity\Unidade
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                unidade_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
