Novosga\Entity\Perfil:
    type: entity
    table: perfis
    repositoryClass: App\Repository\ORM\PerfilRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            scale: 0
            length: 50
            unique: false
            nullable: false
            precision: 0
        descricao:
            type: string
            scale: 0
            length: 150
            unique: false
            nullable: false
            precision: 0
        modulos:
            type: simple_array
            nullable: true
        createdAt:
            type: datetime
            column: created_at
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
    lifecycleCallbacks: {  }
    entityListeners:
        App\Listener\ORM\PerfilListener: ~
