Novosga\Entity\Usuario:
    type: entity
    table: usuarios
    repositoryClass: App\Repository\ORM\UsuarioRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        login:
            type: string
            length: 30
            unique: true
            nullable: false
        nome:
            type: string
            length: 20
            unique: false
            nullable: false
        sobrenome:
            type: string
            length: 100
            unique: false
            nullable: false
        email:
            type: string
            length: 150
            unique: true
            nullable: true
        senha:
            type: string
            length: 128
            unique: false
            nullable: false
        ativo:
            type: boolean
            nullable: false
        ultimoAcesso:
            type: datetime
            unique: false
            nullable: true
            column: ultimo_acesso
        ip:
            type: string
            length: 15
            unique: false
            nullable: true
        sessionId:
            type: string
            scale: 0
            length: 50
            unique: false
            nullable: true
            precision: 0
            column: session_id
        algorithm:
            type: string
            length: 10
            unique: false
            nullable: false
        admin:
            type: boolean
            nullable: false
        salt:
            type: string
            length: 60
            nullable: true
        createdAt:
            type: datetime
            column: created_at
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
        deletedAt:
            type: datetime
            column: deleted_at
            nullable: true
    oneToMany:
        lotacoes:
            targetEntity: Novosga\Entity\Lotacao
            cascade: ['all']
            mappedBy: usuario
            orphanRemoval: true
    lifecycleCallbacks: {  }
    entityListeners:
        App\Listener\ORM\UsuarioListener: ~
