Novosga\Entity\Servico:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [nome, deletedAt]
            message: Já existe um serviço com esse código
            ignoreNull: false
    properties:
        nome:
            - NotBlank: ~
            - Length:
                max: 50
                min: 3
        descricao:
            - NotBlank: ~
            - Length:
                max: 250
        peso:
            - NotNull: ~
