Novosga\Entity\Unidade:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: nome
            message: Já existe uma unidade com esse código
    properties:
        nome:
            - NotBlank: ~
            - Length:
                max: 50
                min: 3
        descricao:
            - NotBlank: ~
            - Length:
                min: 1
                max: 250
        ativo:
            - NotNull: ~
